defaults:
  enabled:        true
  default_locale: en-US
  default_level:  0
  application:
    host:         http://localhost:3000
    key:          default
    secret:       12345
  logger:
    enabled:      true
    path:         /log/tr8n.log
  cache:
    enabled:      false
    adapter:      file
    path:         /cache
    version:      1
    timeout:      3600
    host:         localhost:11211
  localization:
    default_day_names:        [Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday]
    default_abbr_day_names:   [Sun, Mon, Tue, Wed, Thu, Fri, Sat]
    default_month_names:      [January, February, March, April, May, June, July, August, September, October, November, December]
    default_abbr_month_names: [Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec]
    custom_date_formats:
      default:                '%m/%d/%Y'            # 07/4/2008
      short_numeric:          '%m/%d'               # 07/4
      short_numeric_year:     '%m/%d/%y'            # 07/4/08
      long_numeric:           '%m/%d/%Y'            # 07/4/2008
      verbose:                '%A, %B %d, %Y'       # Friday, July  4, 2008
      monthname:              '%B %d'               # July 4
      monthname_year:         '%B %d, %Y'           # July 4, 2008
      monthname_abbr:         '%b %d'               # Jul 4
      monthname_abbr_year:    '%b %d, %Y'           # Jul 4, 2008
      date_time:              '%m/%d/%Y at %H:%M'   # 01/03/1010 at 5:30