tr8n:
  enabled:        true
  default_locale: en-US
  default_level:  0
  application:
    host:         http://localhost:3000
    key:          default
    secret:       12345
  logger:
    enabled:      true
    path:         /log/tr8n.log
  cache:
    enabled:      false
    adapter:      file
    path:         /cache
    version:      1
    timeout:      3600
